# application-example.properties

spring.data.mongodb.uri=mongodb+srv://<username>:<password>@<cluster-url>/?retryWrites=true&w=majority
server.servlet.context-path=/mmdbanking
spring.data.mongodb.database=MMDBankingCluster